[package]
name = "white-whale"
version = "1.2.0"
edition.workspace = true
authors = ["Kerber0x <kerber0x@protonmail.com>, Edward E <e3lris@outlook.com>"]
description = "Common White Whale types and utils"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
default = ["dex", "flashloans"]
injective = []
dex = []
flashloans = []
rewards = []
bonding = []

[dependencies]
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
cosmwasm-schema.workspace = true
cw20.workspace = true
protobuf.workspace = true
uint.workspace = true

